//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCreation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectCreation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c389bb2... stable resource files
=======
>>>>>>> 819fb48c66fd4bd821537562bc3ebc757e7c21b2
        
        /// <summary>
        ///   Looks up a localized string similar to O diretório selecionado para armazenar os logs não existe. Deseja criá-lo?.
        /// </summary>
        internal static string FrmCriarTeamProject_btnCriar_txtLogPath_DirectoryNotFoud_Create {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_btnCriar_txtLogPath_DirectoryNotFoud_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar o Team Project {0}.
        /// </summary>
        internal static string FrmCriarTeamProject_CouldNotCreateTeamProject {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_CouldNotCreateTeamProject", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0bdf4ed... icons and texts
=======
>>>>>>> 819fb48c66fd4bd821537562bc3ebc757e7c21b2
        ///   Looks up a localized string similar to Você tem linhas em branco no seu arquivo..
        /// </summary>
        internal static string FrmCriarTeamProject_EmptyLines {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_EmptyLines", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c389bb2... stable resource files
=======
>>>>>>> 0bdf4ed... icons and texts
=======
>>>>>>> 819fb48c66fd4bd821537562bc3ebc757e7c21b2
        ///   Looks up a localized string similar to O arquivo selecionado é inválido: {0} {1}.
        /// </summary>
        internal static string FrmCriarTeamProject_InvalidListFile {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_InvalidListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O caminho {0} informado para arquivo de lista de Team Projects é inválido..
        /// </summary>
        internal static string FrmCriarTeamProject_InvalidListPath {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_InvalidListPath", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0bdf4ed... icons and texts
=======
>>>>>>> 819fb48c66fd4bd821537562bc3ebc757e7c21b2
        ///   Looks up a localized string similar to Você não usou as flags para criação de Site Sharepoint corretamente..
        /// </summary>
        internal static string FrmCriarTeamProject_InvalidSharepointSiteFlag {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_InvalidSharepointSiteFlag", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c389bb2... stable resource files
=======
>>>>>>> 0bdf4ed... icons and texts
=======
>>>>>>> 819fb48c66fd4bd821537562bc3ebc757e7c21b2
        ///   Looks up a localized string similar to Você precisa selecionar um Template de Processo a ser usado nos Team Projects..
        /// </summary>
        internal static string FrmCriarTeamProject_ProcessTemplateNotSelected {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_ProcessTemplateNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao.
        /// </summary>
        internal static string FrmCriarTeamProject_TextFile_No {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_TextFile_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string FrmCriarTeamProject_TextFile_Yes {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_TextFile_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo informado para extrair a lista de Team Projects está vazio..
        /// </summary>
        internal static string FrmCriarTeamProject_txtCaminho_Arquivo_Vazio {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_txtCaminho_Arquivo_Vazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos texto (*.txt)|*.txt.
        /// </summary>
        internal static string FrmCriarTeamProject_txtCaminho_FilterFiles {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_txtCaminho_FilterFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa informar a URL da Coleção..
        /// </summary>
        internal static string FrmCriarTeamProject_txtCollectionUrl_Precisa_Ser_Informada {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_txtCollectionUrl_Precisa_Ser_Informada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa informar o caminho para a pasta que vai armazenar os logs..
        /// </summary>
        internal static string FrmCriarTeamProject_txtLogPath_Required {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_txtLogPath_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo contém linhas sem informações para criação de projeto..
        /// </summary>
        internal static string FrmCriarTeamProject_YourFileContainsInvalidLines {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_YourFileContainsInvalidLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu arquivo contém linha(s) com menos de duas colunas..
        /// </summary>
        internal static string FrmCriarTeamProject_YourFileContainsLessThan2Lines {
            get {
                return ResourceManager.GetString("FrmCriarTeamProject_YourFileContainsLessThan2Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string MessageBox_TituloGenericoErro {
            get {
                return ResourceManager.GetString("MessageBox_TituloGenericoErro", resourceCulture);
            }
        }
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> a13d8b9... continuing combo to select process template
=======
>>>>>>> c389bb2... stable resource files
=======
>>>>>>> 819fb48c66fd4bd821537562bc3ebc757e7c21b2
    }
}
